### ISSUE TITLE
Typo in CLI command in README when listing peers

### ISSUE THREAD

**Issue by randyridgley** [aws-samples/ipfs-cluster-fargate#12]
Minor thing, but when running through the doc I get an error `error parsing secret: encoding/hex: invalid byte: U+002D '-'` and it wasn't obvious.

Under ***List all IPFS peers*** you have:

`export SECRET=221813dc706c2d1baaf0a15a8710e3c5e2072783c49d214243540044f21a7315`

and it should be 

`export CLUSTER_SECRET=221813dc706c2d1baaf0a15a8710e3c5e2072783c49d214243540044f21a7315`

**Comment by lubao** [comment]
Thanks for reporting the typo and it has been fixed.
